import { FileSpreadsheet } from 'lucide-react';
import MinmaxPreviewTable from './MinmaxPreviewTable';
import MinmaxSummary from './MinmaxSummary';
import MinmaxWarnings from './MinmaxWarnings';

export default function MinmaxResultCard({ title, result, emptyText }) {
  const rows = result?.rows || [];
  return <div className="bg-[#111111] border border-white/10 rounded-[32px] p-6 md:p-8 shadow-2xl flex-1 min-h-64"><div className="flex items-center justify-between mb-6"><h2 className="text-lg md:text-xl font-bold text-white tracking-wide">{title}</h2>{result && <span className={`px-3 py-1.5 rounded-xl text-[10px] font-bold tracking-widest uppercase border ${result.success ? 'bg-emerald-500/10 text-emerald-300 border-emerald-400/20' : 'bg-red-500/10 text-red-300 border-red-400/20'}`}>{result.success ? 'Done' : 'Failed'}</span>}</div>{!result ? <div className="h-40 flex flex-col items-center justify-center text-white/20 gap-4"><div className="p-6 rounded-full bg-white/5 border border-white/5"><FileSpreadsheet size={48} strokeWidth={1} /></div><p className="text-sm font-medium tracking-wide">{emptyText}</p></div> : result.success ? <div className="flex flex-col gap-5"><p className="text-white font-semibold">{result.message}</p><MinmaxSummary summary={result.summary} /><MinmaxWarnings warnings={result.warnings} alarms={result.alarms} />{result.files && <pre className="bg-black/40 border border-white/10 rounded-3xl p-5 text-white/70 text-xs overflow-auto">{JSON.stringify({ files: result.files }, null, 2)}</pre>}{result.recommendation && <pre className="bg-black/40 border border-white/10 rounded-3xl p-5 text-white/70 text-xs overflow-auto">{JSON.stringify({ recommendation: result.recommendation, candidates: result.candidates }, null, 2)}</pre>}<MinmaxPreviewTable title={`First 20 ${title} Rows`} rows={rows} /></div> : <div className="bg-black/40 border border-white/10 rounded-3xl p-5 overflow-auto custom-scrollbar"><p className="text-white font-semibold mb-3">{result.message}</p><pre className="text-white/60 text-xs leading-6 whitespace-pre-wrap">{JSON.stringify(result, null, 2)}</pre></div>}</div>;
}
